version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PIPE_DRIVE_API_KEY=your_api_key
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devops_db
    ports:
      - "5432:5432"
