basePath: /
definitions:
  api.CreateDealResponse:
    properties:
      data: {}
      success:
        example: true
        type: boolean
    type: object
  api.GetDealsResponse:
    properties:
      additional_data: {}
      data: {}
      success:
        example: true
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a simple API for the DevOps challenge.
  title: DevOps Challenge API
  version: "1.0"
paths:
  /deals:
    get:
      consumes:
      - application/json
      description: Returns all deals from Pipedrive
      parameters:
      - example: cursor_token
        in: query
        name: cursor
        type: string
      - example: custom_field_1,custom_field_2
        in: query
        name: custom_fields
        type: string
      - example: 123
        in: query
        name: filter_id
        type: integer
      - example: 1,2,3
        in: query
        name: ids
        type: string
      - example: next_activity_id,last_activity_id
        in: query
        name: include_fields
        type: string
      - example: 100
        in: query
        name: limit
        type: integer
      - example: 101
        in: query
        name: org_id
        type: integer
      - example: 456
        in: query
        name: owner_id
        type: integer
      - example: 789
        in: query
        name: person_id
        type: integer
      - example: 202
        in: query
        name: pipeline_id
        type: integer
      - example: update_time
        in: query
        name: sort_by
        type: string
      - example: desc
        in: query
        name: sort_direction
        type: string
      - example: 303
        in: query
        name: stage_id
        type: integer
      - example: open,winner
        in: query
        name: status
        type: string
      - example: "2025-01-01T10:20:00Z"
        in: query
        name: updated_since
        type: string
      - example: "2025-01-02T10:20:00Z"
        in: query
        name: updated_until
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.GetDealsResponse'
      summary: Get all deals
      tags:
      - deals
    post:
      consumes:
      - application/json
      description: Creates a new deal in Pipedrive using query parameters
      parameters:
      - example: "2021-01-01T00:00:00Z"
        in: query
        name: add_time
        type: string
      - example: "2021-01-01T00:00:00Z"
        in: query
        name: close_time
        type: string
      - example: USD
        in: query
        name: currency
        type: string
      - example: "2021-01-01"
        in: query
        name: expected_close_date
        type: string
      - example: false
        in: query
        name: is_deleted
        type: boolean
      - example: 1,2,3
        in: query
        name: label_ids
        type: string
      - example: Lost Reason
        in: query
        name: lost_reason
        type: string
      - example: "2021-01-01T00:00:00Z"
        in: query
        name: lost_time
        type: string
      - example: 1
        in: query
        name: org_id
        type: integer
      - example: 1
        in: query
        name: owner_id
        type: integer
      - example: 1
        in: query
        name: person_id
        type: integer
      - example: 1
        in: query
        name: pipeline_id
        type: integer
      - example: 90
        in: query
        name: probability
        type: number
      - example: "2021-01-01T00:00:00Z"
        in: query
        name: stage_change_time
        type: string
      - example: 1
        in: query
        name: stage_id
        type: integer
      - example: open
        in: query
        name: status
        type: string
      - example: Deal Title
        in: query
        name: title
        required: true
        type: string
      - example: "2021-01-01T00:00:00Z"
        in: query
        name: update_time
        type: string
      - example: 200.5
        in: query
        name: value
        type: number
      - example: 7
        in: query
        name: visible_to
        type: integer
      - example: "2021-01-01T00:00:00Z"
        in: query
        name: won_time
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.CreateDealResponse'
      summary: Add a new deal
      tags:
      - deals
swagger: "2.0"
