basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a simple API for the DevOps challenge.
  title: DevOps Challenge API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
